name: Docker Image CI

on:
  workflow_dispatch

jobs:
  ubuntu:
    name: create docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - run: tree
      - run: docker images
